### PR TITLE
Feature/redshift support

### PR DESCRIPTION
**Pull request by neoaisac**
Adds initial AWS Redshift support for RoundhousE.

### CODE REVIEW

**Comment by neoaisac** [comment]
@erikbra I thought I'd do the PR as we're already running locally with an alpha version for Redshift based on this code. I'd like to have someone reviewing the code (it's my first public OSS commit in years) :)

**Comment by erikbra** [comment]
@neoaisac Thanks a lot for your PR. And terribly sorry for the long time before any feedback from my part. Work and other parts of my life has made RoundhousE bump down the list of priorities. I think your PR looks nice and clean.

Just a quick question, I don't know Amazon Redshift, and I just wondered why you have made the implementations subclass NpgSql? Is Redshift based on PostgreSQL?

**Comment by neoaisac** [comment]
Hi @erikbra. Redshift uses a somewhat compatible interface based on PostgreSQL 8.0.2, however it's not 100% PostgreSQL. There are some things that don't work, and some things that don't work as expected in PostgreSQL standard.

Maybe this helps:

- https://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html
- http://www.npgsql.org/doc/compatibility.html

**Comment by erikbra** [comment]
Thanks a lot for the update, @neoaisac . I tried reading up on it on the Amazon Redshift website, but my google fu wasn't up to par, apparently :)

I presumed it was based upon PostgreSQL, since you made it inherit that, I just wanted to be sure and know a bit more before merging. 

Again, thanks a lot for your PR.

**Pull request merged**
