### PR TITLE
Replace StructureMap DI library with Ninject 

### PR DESCRIPTION
**Pull request by phillee007**
Replace StructureMap DI library with Ninject in order to fix issues with StructureMap exceptions when running on .Net Core. I figured this was worth it given Ninject is under active development and works in other .Net Core apps

Update tests also

Have tested locally but not yet on large project

Should fix issue #327

### CODE REVIEW

**Comment by phillee007** [comment]
@erikbra @BiggerNoise Hopefully this can help. I've run it via rh.exe against the sample on a machine with full .net framework installed and it worked, what other testing should I do?

**Comment by BiggerNoise** [comment]
I'll take a look at this at some point, but honestly, my inclination is to just get rid of the DI framework completely. I just don't think they make any sense for a small CLI application.

**Comment by phillee007** [comment]
Ok thank you. I guess in the short-term without this we can't actually use RH, so need it as a way to move forward. It seems like more work to remove the DI framework than to just swap it out (which it looks like RH was already built to allow via the container abstraction)?

**Comment by ferventcoder** [comment]
Definitely built with a container abstraction to make it easy to swap - I am curious why Ninject - from when I used it in the past I've found it to be the worst performing...

**Comment by ferventcoder** [comment]
Sorry, posted that without the hard data - http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison. This was something started back in 2011, but the guy has a GitHub project here and has kept it up to date with results as each framework has gotten better. It's one of the things that made me choose Simple Injector back when I was looking for a replacement due to poor performance.

**Comment by phillee007** [comment]
@ferventcoder because Ninject works in .Net core and has large industry usage. Performance of the DI framework didn't really factor into my thought process given the nature of RH (making db connections which are inherently slow)

**Comment by erikbra** [comment]
Very happy to have more contributors, @phillee007!! I love to replace "dead" dependencies with actively developed ones. However, @BiggerNoise has a point, do we really need a DI _container_ for this project? DI, yes, but maybe we can just wire it up in the `Main()` or somewhere nearby. I'll have a quick look at how much work it would be to skip the container altogether, and get back to this PR if removing it is too big a task. I'm very keen on getting the 1.0 release out :)

**Comment by erikbra** [comment]
I would prefer merging #335 in favour of this one. The DI needs are minimal in RoundhousE, and removing a dependency altogether instead of replacing it with another is better, ihmo. Any opinions?

**Comment by BiggerNoise** [comment]
@phillee007 - Thank you for the contribution, even if we decided to head a different direction.

**Comment by phillee007** [comment]
No worries - I'm glad it got resolved either way.

**Pull request closed without merging**
