### PR TITLE
Normalizing line endings prior to computing hash.

### PR DESCRIPTION
**Pull request by rfbain**
Fix to issue #247

### CODE REVIEW

**Comment by drusellers** [comment]
@ChrisMissal @ferventcoder is this good to come in?

**Comment by ferventcoder** [comment]
It is, but the commit needs a body that really explains what this fixes and why.

**Comment by ferventcoder** [comment]
@rfbain apologies for not taking a look sooner, any chance you can address my comment about having a commit body to go along with that summary? 

For details on how to format that, this is a really good explanation and has links to reasoning behind it - https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#prepare-commits

Alternatively @drusellers @ChrisMissal if you want to rebase the commit you can pull it in with the good message.

**Comment by rfbain** [comment]
(GH-247) Normalize Line Endings Prior to Calculating and Saving the Hash

Previously, the hash was calculated based on the line endings in the source file.  The hash was then saved to the database without benefit of line ending normalization.  Code run at a later time to compare the hash of the updated file checked if normalized line endings in the updated file matched the original file.

Without the change, there is a problem when the original file has a mix of windows and unix line endings.  Its hash will not match the hash of the updated file.  The script with changes limited to line ending changes will be run when it should be skipped.

**Comment by ferventcoder** [comment]
@rfbain and this will work with scripts already calculated as well, if I understand correctly.

**Comment by rfbain** [comment]
No.  For scripts that have a mix of line endings and have hash values that were calculated prior to this change, my fix will not solve the problem by itself.  Nor will it make the problem worse than it was before.  I thought about adding code to read the original source code from the database and recalculating the hash, but I did not want to introduce that significant a performance hit to the process.  I think the best option to fix old hash values would be to run roundhouse with the baseline option.

**Comment by BiggerNoise** [comment]
Thank you for the contribution. I have made changes in the database migrator that supersede this P/R. Putting the code there allows checking a number of cases and allows compatibility with previously calculated scripts.

**Pull request closed without merging**
