### PR TITLE
Upgrade from VS2010 .NET 3.5 to VS2013 .NET 4.5

### PR DESCRIPTION
**Pull request by ChrisMissal**
The only thing that wasn't super straightforward was the need to upgrade ILMerge to address a bug in v4.0+.

### CODE REVIEW

**Comment by ChrisMissal** [comment]
Closes #178 

Can I get a quick look @ferventcoder or @BiggerNoise?

**Comment by ferventcoder** [comment]
LGTM

ILMerge has a key you can pass to it to ensure .NET 4 platform:

https://github.com/chocolatey/choco/blob/master/.build.custom/ilmerge.replace.build#L28

`/targetplatform:v4`

**Comment by ferventcoder** [comment]
It looks like you may need to address that as well in the following places:
* https://github.com/chucknorris/roundhouse/blob/master/build.custom/ilmerge.replace.build#L30-L31
* https://github.com/chucknorris/roundhouse/blob/master/build.custom/ilmergeDLL.build#L34-L35

**Comment by ferventcoder** [comment]
branches in the upstream.... :/

**Pull request merged**
