### PR TITLE
Add support for not Altering database

### PR DESCRIPTION
**Pull request by erikbra**
To be able to run RoundHouse without having logon rights to the master database, I added a flag -da/-dna, which means "do not alter", so that roundhouse does not try an admin login if not needed.

### CODE REVIEW

**Comment by ferventcoder** [comment]
There are too many changes here not related to your ticket.

**Comment by ferventcoder** [comment]
This is the only commit that should be in this branch (please don't use your master branch) - https://github.com/erikbra/roundhouse/commit/fae70577087de4493896d28db5dcecafdbf6bbcc

**Comment by erikbra** [comment]
You know, you are correct. Sorry. Shouldn't have included the Visual Studio build configuration changes changeset. I'm not very experienced in pull requests either. Do you want pull requests in a separate branch as well?

Should I make a branch from you master, merge only this changeset, and make another pull request? Or how do you wish to handle it?

Sorry for the mess.

**Comment by ChrisMissal** [comment]
@erikbra Please create a new branch from `chucknorris/roundhouse` `master`, then you can cherry-pick commit fae7057 into that. From there you can push your new branch and create a PR from that.

Let me know if that's not clear, I'm happy to help.

**Comment by ferventcoder** [comment]
Unfortunately when you create your topic branch and push it, Github no longer allows you to change the target branch or the branch your PR comes from. So you will create a new one, then comment on the new one with `Supersedes #182` so the conversations are linked, and close this one.

**Comment by erikbra** [comment]
Created a new pull request with just the commit in question, and in its own branch. Sorry for the delay, have been very busy lately. https://github.com/chucknorris/roundhouse/pull/187

**Comment by erikbra** [comment]
Did you get the new pull request?
https://github.com/chucknorris/roundhouse/pull/187

2015-04-02 23:12 GMT+02:00 Rob Reynolds <notifications@github.com>:

**Comment by ferventcoder** [comment]
Superseded by #187

**Pull request closed without merging**
