### PR TITLE
Converted all projects to AnyCpu

### PR DESCRIPTION
**Pull request by LodewijkSioen**
This will update all the csproj files to build for 'AnyCpu'. Everything builds and still works on Oracle and MsSql.

### CODE REVIEW

**Comment by BiggerNoise** [comment]
Somewhere along the way someone else made the conversion, so this has been overcome by events. Thank you for the contribution though.

**Comment by bladeoflight16** [comment]
@BiggerNoise This should not have been done without switching to the fully managed .NET Oracle client. (#171) With the Any CPU configuration, it's not predictable which Oracle native binaries you need.

**Comment by BiggerNoise** [comment]
It's still x86 as of 0.8.8 (I mistakenly marked this closed).

The next version will be Any CPU (we're working on that now). I would welcome a P/R to the managed .NET driver for Oracle (I can't do it because I don't have access to an Oracle environment).

If you're willing to do this,  I would ask that you give us a couple of days to get P/R #285 finished, merging will be a nightmare if you don't.

**Comment by erikbra** [comment]
@bladeoflight16 - Please see #298 - are you able to help with that one?

**Comment by erikbra** [comment]
We're good to close this one, right, @BiggerNoise ?

**Comment by BiggerNoise** [comment]
We can leave it closed.

**Comment by erikbra** [comment]
It was already closed, yes. Sorry :D

**Pull request closed without merging**
