### PR TITLE
Issue 243 - nunit version

### PR DESCRIPTION
**Pull request by erikbra**
As requested in Pull Request #271 , I have converted the tests to NUnit instead of xUnit. I have used TinySpec, as in Chocolatey tests, and tried to change as little as possible. Goal was to easily run tests in a modern development environment (Visual Studio), without having to use a command-line test runner. 

Could you please take a look at this pull, @ferventcoder , and see if you like this one better than #271?

### CODE REVIEW

**Comment by BiggerNoise** [comment]
I will look at pulling this in as soon as I am sure that I did not mess up the 0.8.7 release.

Thank you so much for the work on this, bear with me for a bit longer.

**Comment by erikbra** [comment]
Lovely, @BiggerNoise. Thanks. I wouldn't want to mess up the 0.8.7 release - it's been in the making for years :)
I say don't stress the merging before the release. There's nothing stopping release 0.8.8 coming in not too long :) 

The build failed because I had used C# 6 features. Any reason we want to stay on C# 5? We can handle this in a separate issue, anyway.

**Comment by erikbra** [comment]
One thing, though. I might have broken some bdd doc generation? I don't know how to test it. But I don't think it has been working for ages, ref. #122.

**Comment by ferventcoder** [comment]
Bdddoc was built to parse xml output from mbunit - so it would be expected to be broken when you switch out the testing framework (and that is okay).

**Pull request merged**
