### PR TITLE
Issue #243: Converted all tests from MBUnit to xUnit

### PR DESCRIPTION
**Pull request by erikbra**
Issue #243: Converted all tests from MBUnit to xUnit (w/FluentAssertions and NSubstitute)

I converted all MBUnit tests to xUnit tests (I think it is a better fit than NUnit, as the `[Fact]` attribute to me is semantically similar to `[Observation]`. I'm not a hard-core BDD-er, so I'm open to that I might have misunderstood things.

I couldn't run `build.bat` or `test.bat` after the conversion, but I'm not very fluent in UppercuT, so I might need some help tweaking the build files. Everything builds fine in Visual Studio, and using MSBuild on the `RoundhousE.sln` file (same version used in `build.bat`.

Please take a look, and tell me what you think. I don't think the conversion involved too many changes, and I think using a test framework that is a) actively maintainted and b) known to most .NET developers is very important.

### CODE REVIEW

**Comment by ferventcoder** [comment]
I was hoping for NUnit, not xUnit. But I will let @BiggerNoise be the decider of this.

**Comment by ferventcoder** [comment]
FWIW, please update the uppercut.config to let it know of the new testing framework, otherwise the build will start failing.

**Comment by erikbra** [comment]
Sorry about the xUnit/Nunit disappointment. I don't think it's too big a change to migrate to NUnit if it's important to you. I didn't find a good fit replacement for the `Observation`  attribute in NUnit (the observations are "statements" in naming), that's why I went for xUnit, but I'm open to discussion, of course :)

**Comment by ferventcoder** [comment]
Minor nitpick - Git has commit summaries and bodies. The summary should be the first line, and around 50 characters. Then skip a line and write a good commit body, wrapping at 72 chars.

**Comment by erikbra** [comment]
Love nitpicking. I will fix. Do you want me to squash the commits into one as well when I have to force push anyway? Or would you like the "Updated Nuget.exe" one to be a separate one, to make history explicit?

**Comment by ferventcoder** [comment]
The preference for me (not sure about others) is that each commit should represent what it is about. If changing nuget.exe has nothing to do with other things you are doing, those are separate commits. 

Squashing comes when you are fixing smaller things and making commits, but all of those commits are really about the same thing (all considered part of an atomic change). "Like fixed compilation errors due to warnings" (acdd64d) is a great candidate for squashing.

**Comment by BiggerNoise** [comment]
I'm assuming that this P/R is obsolete since you created the Nunit version. If I'm wrong on that, please reopen.

**Comment by erikbra** [comment]
Hi, yes, this one is obsolete (or, if you wish, an alternative), since you have merged the NUnit one. Great to have some merges again! :) Closing this one is just fine.

**Pull request closed without merging**
