### PR TITLE
Fixed Issue #306 - added roundhouse.lib.merged

### PR DESCRIPTION
**Pull request by erikbra**
Added another project, just for the merge of all the DLLs into one for
Nuget packaging. Made more of the original Nuget dependencies proper
dependencies of roundhouse.lib instead of merging some of them. I think
merging them might lead to problems if someone uses both roundhouse.lib
and one of the original dependency nuget packages.

### CODE REVIEW

**Comment by BiggerNoise** [comment]
@erikbra This looks good to me. I can see the classes in a sample project that I created. I want to give @drjaydenm a chance to verify things before I merge it. I also want to give @ferventcoder a chance to chime in.

I'll merge and make release 0.9.1 as soon as we hear from those guys.

Thanks!

**Comment by drjaydenm** [comment]
Hi guys, thanks for getting onto this quickly. I use this for projects at work so I'll be able to test it out on Monday and let you know how it goes. Thanks!

**Comment by drjaydenm** [comment]
@erikbra @BiggerNoise Just checked this out and it looks like it has all the classes in the DLL now. Thanks

**Comment by BiggerNoise** [comment]
@drjaydenm Thank you. I'm going to merge this now and cut a release tomorrow or Tuesday.

**Pull request merged**
