### PR TITLE
Added rh.bat and .zip packaging

### PR DESCRIPTION
**Pull request by erikbra**
It't easier to test the netcore version on Windows if distributed as a
.zip, and with at .bat file to execute.

### CODE REVIEW

**Comment by erikbra** [comment]
@BiggerNoise don't you think it's a good idea to include these, if we want people testing the core version on Windows too? ( I wish we could make the merge for .net core work too, but I think we're at a combination of immature tools and some ancient dependencies that make the tools not work for us yet, including log4net).

**Comment by ferventcoder** [comment]
rh.bat I like, I am glad to see the zip packaging make it back in after a brief hiatus with the migration away from uppercut. One thing that is important to note is that a nuget package is simply a zip package as well.

**Comment by ferventcoder** [comment]
Simply - well close to simply, it has a few more things added but it is essentially something you can rename from .nupkg to .zip and uncompress.

**Comment by erikbra** [comment]
Good point about the zip vs nuget.

It is fair to remark that the .nupkg and the .zip file contains totally different bits as of now. The .nupkg contains a single, ILMerge'd rh.exe, for .NET Desktop (e.g. .NET 4.6.1), while the zip file contains the .net core version. This sadly cannot be merged into a single binary at the time, so it is a load of files. And it doesn't include Oracle or Access support (couldn't get those to work on core).

It does however run on all platforms supporting .NET Core.

So, for Windows, I think I would prefer the merged version for now if I were an end-user. But the .bat is there for the users to be able to test the .net core version on windows too.

**Comment by ferventcoder** [comment]
👍

**Pull request merged**
