### PR TITLE
Feature/user token replacement

### LINKED ISSUE #140: [Enhancement] Customize Token Replacement
How can I set and replace custom tokens.

My current need is to tokenize the absolute path of a data file for bulk insert.

### PR DESCRIPTION
**Pull request by guilhermeando**
I need a simple user token replacement:
- added new argument "ut=|usertokens="
- receive a path to a file which content follow the syntax:

```
UserId=123
UserName=Some Name
```
- parse the file content to a Dictionary<string, string> into ConfigurationPropertyHolder.UserTokens
- when creating a dictionary from configuration in TokenReplacer.create_dictionary_from_configuration, check for the property UserTokens and add all properties to the final dictionary

I couldn't be able to run my new tests through test.bat. Is there any place explaining how to add more unit tests?

Closes #140

### CODE REVIEW

**Comment by drusellers** [comment]
Any updates on this? ;P

**Comment by ferventcoder** [comment]
The code looks to be in good shape, but haven't heard back on getting it updated. @guilhermeando ping?

**Comment by ferventcoder** [comment]
Hello @guilhermeando, I'd hate to close this due to lack of updates because this feature would be really useful to the community at large.

**Comment by guilhermeando** [comment]
hey Rob,

sorry about that!
I have been very busy and totally forgot about this.
I'll work on it this weekend and let you know how far I am to complete.

cheers,
guilherme

**Comment by ferventcoder** [comment]
@guilhermeando Awesome! :)

**Comment by dquser** [comment]
Hey there - our team is also looking forward to custom token replacements. Another alternative we thought about is to prefix the custom tokens with a special keyword or character - for example, "@". So if we want to pass (say) a custom username or password, we would pass /@Username=value /@Password=value. We believe that would also be an easy addition to the source code. But @guilhermenado, if you got this, we'll just wait. Thanks!

**Comment by guilhermeando** [comment]
Hey everyone,

I had a look in my code and the idea was just use the same token
replacement mechanism *{{someVariable}}* to inject custom values in the
scripts.
The solution at this point:
- receive a file with variables in a format
variable=value
variable2=value2
variable3=value3
- I need to review the unit tests, I remember that I had problems to run
the tests last time...

I'll try working on it during the week and I'll update my progress on it.

Cheers,
Guilherme

**Comment by drusellers** [comment]
:+1:

**Comment by ferventcoder** [comment]
@guilhermeando if you want, check out the evolution of this that I've done in choco - 

* https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure/tokens/TokenReplacer.cs
* https://github.com/chocolatey/choco/blob/master/src/chocolatey.tests/infrastructure/tokens/TokenReplacerSpecs.cs

However I also worked on something that would just allow a dictionary.

* https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure/commands/ExternalCommandArgsBuilder.cs
* https://github.com/chocolatey/choco/blob/master/src/chocolatey.tests/infrastructure/commands/ExternalCommandArgsBuilderSpecs.cs

**Comment by dquser** [comment]
Hi everyone - my team is really needing this feature but we wouldn't want to create a separate branch. Would it be okay if I try to continue @guilhermeando's work? Thanks.

**Comment by ferventcoder** [comment]
@dquser Sure.

**Comment by ferventcoder** [comment]
When you file the new PR, just add "Supersedes #166" in the PR message.

**Comment by dquser** [comment]
Thanks Rob! I will.

**Comment by guilhermeando** [comment]
hey guys, sorry about that, I'm very busy in work and will not be able to
finish the stuff. Feel free to continue it.

**Comment by dquser** [comment]
Hey there guys. Well I checked out @guilhermeando's changes (great work!). It builds successfully and it passes all unit tests. I'm new to contributing on GitHub - I tried to push my changes to the master branch but I get "forbidden". Should I create a new branch for this? I appreciate your help. Thank you!

**Comment by ferventcoder** [comment]
@dquser You should start with your own fork and make changes in a branch off of master (we call these feature branches). Then you push that to your own fork and issue a pull request from this repository.

Check out the following resources:

* https://help.github.com/articles/using-pull-requests/
* https://help.github.com/articles/working-with-forks/
* https://help.github.com/articles/creating-a-pull-request/

**Comment by dquser** [comment]
Thank you so much!

**Comment by dustinfineout** [comment]
Any update on this feature? My team would like to use custom tokens in our scripts.

**Comment by BiggerNoise** [comment]
Superseded by https://github.com/chucknorris/roundhouse/pull/231

**Pull request closed without merging**
