### PR TITLE
Don't run SQL if /dryrun flag set

### PR DESCRIPTION
**Pull request by jordanwallwork**

### CODE REVIEW

**Comment by ferventcoder** [comment]
I thought maybe there was another PR already out for this?

**Comment by ferventcoder** [comment]
There are actually about 4

**Comment by jordanwallwork** [comment]
Have any been pulled then? It's a nuisance having to make this change whenever I update

**Comment by BiggerNoise** [comment]
OK. This is silly, let's pick one and merge it. #189 has the virtue of simplicity, just fixing the bug,

#111 and #124 also implement baseline. Do we want that as well? #124 is a more extensive refactoring, but it looks like it starts to move the logic in a better direction. It's starting to get tangled in there.

@ferventcoder - I'm dusting off my C# chops (hide the women and children). I don't have super strong feelings about any of these. If you or @ChrisMissal want to weigh in, just assign one of these to me and I will verify it and merge it for the weekend.

**Comment by BiggerNoise** [comment]
Pulled in #111  instead, but thank you very much.

**Comment by jordanwallwork** [comment]
Great news, thanks

**Pull request closed without merging**
