### PR TITLE
Updated SQL Server CE with feedback from ferventcoder.

### PR DESCRIPTION
**Pull request by eavonius**
Supersedes #133.

Rob, I'm creating this with what I have now. It's from a different branch as you suggested (sorry about that). I'm looking for a couple replies on comments with the previous PR, when I handle those I'll fix those issues and update this, at which point we can nuke the old one.

Thanks for your help.

### CODE REVIEW

**Comment by ErikEJ** [comment]
@ferventcoder Anything I can do to get this PR accepted? Create a new one?? 
It would be a great addition to the tool, and I have frequent request for how to solve the issue that RoundhousE deals with,

**Comment by ferventcoder** [comment]
@ErikEJ I think creating a new PR would shepherd this along. This one was pretty good but will need updates.

**Comment by BiggerNoise** [comment]
@ferventcoder What, specifically, needs to be updated to pull this in. To clear the backlog, I'm letting minor stylistic stuff slide, but if something is really off, I don't want to pull it in in haste.

**Comment by eavonius** [comment]
Feel free to go nuts with tweaking this PR, it's so old I barely remember what I did here (probably nothing stellar). Thanks for catching up on all these old PRs!

**Comment by ferventcoder** [comment]
Honestly I'm not sure what needs to be done. But I like the general direction of this so I'm game for pulling it in and then making adjustments.

**Comment by ErikEJ** [comment]
Happy to contribute any "adjustments" once it is in!

**Comment by BiggerNoise** [comment]
Excellent. I'll try and get it pulled in tonight.

**Comment by ErikEJ** [comment]
Nice to get this done 3 years before extended support stops!

**Comment by BiggerNoise** [comment]
OK. I'm in a bit of a pickle on this one. The original repository is gone and github is not allowing me to download the patch.

I'll cycle back eventually, but it would really grease the skids if someone could recreate the P/R so I can merge it in. I think if you can just reproduce the work here, I can merge without much difficulty. There's supposed to be a merge conflict on the solution, but I can get through that easily enough.

**Comment by ErikEJ** [comment]
@BiggerNoise  You mean reconstruct the PR and resubmit? In that case I am game...

**Comment by ErikEJ** [comment]
PR submitted 😄

**Comment by BiggerNoise** [comment]
Superseded by https://github.com/chucknorris/roundhouse/pull/277

**Pull request closed without merging**
