### PR TITLE
Issue240 trim version file contents

### PR DESCRIPTION
**Pull request by macfarmw**
Fixed issue 240 and created supporting unit test.

### CODE REVIEW

**Comment by ferventcoder** [comment]
This is perfect. Would you mind squashing that down to one commit for me?

If this is above and beyond your git abilities, let me know, we can certainly do this for you. It may take a bit longer to pull in though.

**Comment by macfarmw** [comment]
git squash --help

Don't worry, I'll figure it out and update the pull request.

**Comment by ferventcoder** [comment]
Please do read through that linked document though. Lots of helpful information in there. :D

**Comment by ferventcoder** [comment]
Ruhroh - did you run into some issues?

**Comment by macfarmw** [comment]
Yes. I got it all messed up with the rebase and some merged changes. I'm starting over so I'll submit a new version of this. I did not realize my action would close the request. My reopen button is disabled so please reopen this if you don't mind.

**Comment by ferventcoder** [comment]
Without the branch no one can reopen it. If you were using a graphical tool to do this, I would suggest going to the command line `git` tool only. 

The graphical tools are okay, but tend to mess things up when you need to do things like rebase.

**Comment by macfarmw** [comment]
Good advice! I hope you don't mind I just started again and submitted a new request #252 with the single commit.

**Pull request closed without merging**
