### PR TITLE
Manged MD5 Implementation to hack FIPS mode

### LINKED ISSUE #249: Roundhouse fails when FIPS mode is enabled
Unfortunately, there is a nasty little feature of Windows Server 2012 (and possibly other versions, but I have not checked) called [FIPS Mode](http://blogs.technet.com/b/secguide/archive/2014/04/07/why-we-re-not-recommending-fips-mode-anymore.aspx). This disabled whatever hash algorithm RoundhousE is using, resulting in the following error from the latest version on NuGet:

```
StructureMap Exception Code:  207
Internal exception while creating Instance '54ceaf40-a5eb-4e95-86b0-a3f804eb57a4' of PluginType roundhouse.migrators.DatabaseMigrator, rh, Version=0.8.6.0, Culture=neutral, PublicKeyToken=null.  Check the inner exception for more details.
StructureMap.StructureMapException: StructureMap Exception Code:  207
Internal exception while creating Instance '54ceaf40-a5eb-4e95-86b0-a3f804eb57a4' of PluginType roundhouse.migrators.DatabaseMigrator, rh, Version=0.8.6.0, Culture=neutral, PublicKeyToken=null.  Check the inner exception for more details. ---> StructureMap.StructureMapException: StructureMap Exception Code:  207
Internal exception while creating Instance '0edb8085-8ed5-4418-b46e-971c2b3f0717' of PluginType roundhouse.cryptography.CryptographicService.  Check the inner exception for more details. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeConstructor(Object[] args, SignatureStruct& signature, IntPtr declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(Object[] args, SignatureStruct signature, RuntimeTypeHandle declaring
Type)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, Cultu
reInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create(String algName)
   at System.Security.Cryptography.MD5.Create()
   at roundhouse.cryptography.MD5CryptographicService..ctor()
   at lambda_method(ExecutionScope , IArguments )
   at StructureMap.Construction.BuilderCompiler.FuncCompiler`1.<>c__DisplayClass2.<CreateBuilder>b__0(IArguments args)
   at StructureMap.Construction.InstanceBuilder.BuildInstance(IArguments args)
   at StructureMap.Pipeline.ConstructorInstance.Build(Type pluginType, BuildSession session, IInstanceBuilder builder)
   --- End of inner exception stack trace ---
   at StructureMap.Pipeline.ConstructorInstance.Build(Type pluginType, BuildSession session, IInstanceBuilder builder)
   at StructureMap.Pipeline.ConstructorInstance.build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.SmartInstance`1.build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.Instance.createRawObject(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.Instance.Build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.ObjectBuilder.ConstructNew(Type pluginType, Instance instance, BuildSession session)
   at StructureMap.Pipeline.ObjectBuilder.Resolve(Type pluginType, Instance instance, BuildSession session)
   at StructureMap.BuildSession.CreateInstance(Type pluginType, Instance instance)
   at StructureMap.BuildSession.<>c__DisplayClass3.<.ctor>b__1()
   at StructureMap.BuildSession.CreateInstance(Type pluginType)
   at StructureMap.BuildSession.GetInstance[T]()
   at roundhouse.infrastructure.app.ApplicationConfiguraton.<>c__DisplayClass5.<build_items_for_container>b__3(IContext
context)
   at StructureMap.Pipeline.LambdaInstance`1.build(Type pluginType, BuildSession session)
   --- End of inner exception stack trace ---
   at StructureMap.Pipeline.LambdaInstance`1.build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.Instance.createRawObject(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.Instance.Build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.ObjectBuilder.ConstructNew(Type pluginType, Instance instance, BuildSession session)
   at StructureMap.Pipeline.ObjectBuilder.Resolve(Type pluginType, Instance instance, BuildSession session)
   at StructureMap.BuildSession.CreateInstance(Type pluginType, Instance instance)
   at StructureMap.BuildSession.<>c__DisplayClass3.<.ctor>b__1()
   at StructureMap.BuildSession.CreateInstance(Type pluginType)
   at StructureMap.Container.GetInstance(Type pluginType)
   at StructureMap.Container.GetInstance[T]()
   at roundhouse.infrastructure.containers.custom.StructureMapContainer.Resolve[TypeToReturn]()
   at roundhouse.infrastructure.containers.Container.get_an_instance_of[TypeToGet]()
   at roundhouse.console.Program.get_migration_runner(ConfigurationPropertyHolder configuration)
   at roundhouse.console.Program.run_migrator(ConfigurationPropertyHolder configuration)
   at roundhouse.console.Program.Main(String[] args)
```

A solution would be to switch to SHA-1, as the .NET SHA-1 algorithm _is_ FIPS approved, but this poses some serious challenges when migrating from Windows Server 2008 R2 to Windows Server 2012. The only solution I can think of would be to re-hash all the scripts already run with an "approved" algorithm, unless there's a FIPS approved MD5 algorithm in .NET.

### PR DESCRIPTION
**Pull request by ronnieoverby**
Fixes #249

### CODE REVIEW

**Comment by ferventcoder** [comment]
This needs specs testing it against the original implementation. Probably a lot of tests to ensure that the output is the same as the original implementation.

**Comment by ronnieoverby** [comment]
Added test for comparing hash outputs to official md5 implementation.

**Comment by BiggerNoise** [comment]
Thanks for the contribution!

**Comment by ronnieoverby** [comment]
You betcha, pal!

**Pull request merged**
